### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by ghost** [sharmavikas4/MERN_BLOG#1]
Hey 🥳! I see that repository is missing code of conduct. I would like to add a code of conduct developed from scratch for your project. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext & level1 Labels.

**Comment by sharmavikas4** [comment]
I like your idea of adding code of conduct. Also i want you to add a contributor.md file for the project. If you can do that it would be great

**Comment by ghost** [comment]
@sharmavikas4 Please review the PR and action accordingly. Please add level1 and gssoc24-ext labels to the PR. Thank you!
