### ISSUE TITLE
Backend issue in the application "cannot Get /"

### ISSUE THREAD

**Issue by Sehrishzarin** [sharmavikas4/MERN_BLOG#12]
![image](https://github.com/user-attachments/assets/cff91ffa-b725-4392-8f59-f12c0035fadc)
this is what it shows when you open the website, i can help in node js backend if needed @sharmavikas4 assign me any task i can help with

**Comment by sharmavikas4** [comment]
There is an already open issued regarding this and someone is working on it. If he doesnot. Omplete it i will assign it to you.

**Comment by Sehrishzarin** [comment]
sure anytime, i can help with react front end also, I'm still looking for projects to contribute into

**Comment by MohassinHussain** [comment]
Hey @sharmavikas4 I can help u with that.

Assign it to me.
