### ISSUE TITLE
New user google auth Duplication Issue

### ISSUE THREAD

**Issue by PAVAN-VANAM** [sharmavikas4/MERN_BLOG#14]
![Untitled](https://github.com/user-attachments/assets/2d96f20f-ac3b-4291-b7e8-cc137c1ee735)

I know how to solve Can U assign this to me @sharmavikas4

**Comment by sharmavikas4** [comment]
This issue can be resolved by removing the email from indexing in your mongodb cluster.

**Comment by PAVAN-VANAM** [comment]
Actually I thought we have to add username field in mongdb
