### ISSUE TITLE
Add License File to Repository

### ISSUE THREAD

**Issue by rahulgithub-web** [sharmavikas4/MERN_BLOG#16]
## Task
1. Choose an appropriate open-source license.
2. Add the `LICENSE` file to the root of the repository.
3. Update `README.md` to include a reference to the license.

#
@sharmavikas4  Please assign this task to me with all the required labels attached to it.

**Comment by sharmavikas4** [comment]
Go ahead @rahulgithub-web

**Comment by sharmavikas4** [comment]
@rahulgithub-web how is the progress going on

**Comment by sharmavikas4** [comment]
No license added @rahulgithub-web
