### ISSUE TITLE
Maintain a Proper Folder Structure for the Server(Backend)

### ISSUE THREAD

**Issue by rahulgithub-web** [sharmavikas4/MERN_BLOG#18]
### Proposal: Maintain a Proper Folder Structure for the Server

I propose restructuring the server-side code to follow a clean, modular, and scalable folder structure. This will help improve readability, maintainability, and future scalability of the project.

#### Proposed Folder Structure:

```bash
/server
  ├── /src
  │   ├── /models         # Contains database models or schemas
  │   ├── /controllers    # Contains all the route controllers
  │   ├── /services       # Contains business logic and services
  │   └── /routes         # Defines API routes and maps them to controllers
  ├── /config             # Configuration files (e.g., database, environment)
  ├── /middleware         # Custom middleware functions
  ├── /utils              # Helper utilities and common functions
  ├── server.js           # Main server entry point
  └── package.json
```

#
@sharmavikas4  Please assign this task to me. I would love to work on this.

Please label this issue with the following tags:
- `hacktoberfest`
- `hacktoberfest2024`
- `hacktoberfest-accepted`
- `documentation`
- `gssoc-ext`

**Comment by geetanjalidubey9** [comment]
pls, assign this task to me.

**Comment by sharmavikas4** [comment]
We have already an issue opened in this regard

**Comment by rahulgithub-web** [comment]
@sharmavikas4 Thanks for the update

**Comment by MohassinHussain** [comment]
Hey @sharmavikas4 I can help you with that!

Assign me.

**Comment by sharmavikas4** [comment]
@MohassinHussain an issue is already open in this regard
