### ISSUE TITLE
Add Github Greeting Bot

### ISSUE THREAD

**Issue by ghost** [sharmavikas4/MERN_BLOG#2]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by sharmavikas4** [comment]
First complete the assigned issue, then create the next issue.

**Comment by ghost** [comment]
@sharmavikas4 I am now ready for this issue. I have raised the PR for the earlier issue. Can I get this assigned please. Thank you!

**Comment by sharmavikas4** [comment]
Go ahead @KiranBaliga

**Comment by ghost** [comment]
@sharmavikas4 Please review the PR and action accordingly. Thank you!

(please add 'gssoc24-ext' & 'level1' label to the PR)
