### ISSUE TITLE
Structure Backend

### ISSUE THREAD

**Issue by PAVAN-VANAM** [sharmavikas4/MERN_BLOG#3]
Hello @sharmavikas4 

your backend all details are under one file index.js it's hard to understand and looks like an unstructured

I would like to structure the whole backend with routings  and MVC architecture

I want to work on this project Can U assign me

**Comment by sharmavikas4** [comment]
Great issue, @PAVAN-VANAM. It will be really appreciable if you are able to structure the project and apply MVC architecture. Go ahead.

**Comment by Riddhi12349** [comment]
hi please assign me this issue

**Comment by sharmavikas4** [comment]
@Riddhi12349 it is already completed by @PAVAN-VANAM
