### ISSUE TITLE
[BUG] App is not loading

### ISSUE THREAD

**Issue by jjaijg** [sharmavikas4/MERN_BLOG#33]
### Description

I was just looking at the repo and trying to explore the app. But looks like it's not loading. 

OS: Windows
Browser: Google Chrome

### Screenshots

![image](https://github.com/user-attachments/assets/3f9c45a8-7f95-450b-8989-337dce995299)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by sharmavikas4** [comment]
@jjaijg there is an issue with deployment it doesnot work when deployed online but works good when deployed locally

**Comment by jjaijg** [comment]
Oh ok. Thanks @sharmavikas4

**Comment by sharmavikas4** [comment]
@jjaijg are you working on it

**Comment by sharmavikas4** [comment]
``
