### ISSUE TITLE
Implementing MVC architecture for the server

### ISSUE THREAD

**Issue by Sonalgupta2005** [sharmavikas4/MERN_BLOG#34]
## Objective:

The objective for this is to refactor the existing application to adhere to the Model-View-Controller (MVC) architecture. This is aimed at improving code maintainability, scalability, and separation of concerns.

I will make models, controllers and routes directory in the server for modularity in the code as everything is written in a single file (index.js) which is making the code difficult to understand for the contributors.

## Scope:

- Model: Define the data structure and business logic. This includes setting up models for various data entities and ensuring proper data validation.

- Routes: Implement routes for the app.

- Controller: Implement controllers that handle user inputs, update the model, and return the correct view. Controllers will act as i

If you want me to make these changes, please assign me this task with the particular labels.

**Comment by sharmavikas4** [comment]
@Sonalgupta2005  we have already implemented the mvc architecture to the server
