### ISSUE TITLE
[Feat] Implementing Category-wise Blogs

### ISSUE THREAD

**Issue by Sonalgupta2005** [sharmavikas4/MERN_BLOG#37]
### Description

I will categorize blogs on the basis of whether it is a travel, health, tech, quotes, books, agricultural, industry, marketing or others type of blogs. For this, I will define category property in the post object of user schema and display the blogs on the basis of its category. If you want me to make these changes, please assign this issue to me with the particular labels.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sharmavikas4** [comment]
You can go ahead @Sonalgupta2005 .
