### ISSUE TITLE
[Feat] :adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by trahulprabhu38** [sharmavikas4/MERN_BLOG#40]
### Description

I want to add a page to showcase all the contributors of this website
@sharmavikas4 can you assign me this issue

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sharmavikas4** [comment]
@T-Rahul-prabhu-38 we already displayed the name of contributors on readme and i don't want to display on the app.
