### ISSUE TITLE
[Feat] MIT LICENSE File is not added

### ISSUE THREAD

**Issue by heizshubham** [sharmavikas4/MERN_BLOG#42]
### Description

MIT LICENSE File should be there for better use.

### Screenshots

<img width="700" alt="image" src="https://github.com/user-attachments/assets/060522a9-a8cb-4d0c-bdc6-44a77721a5d6">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sharmavikas4** [comment]
@heizshubham you can proceed

**Comment by heizshubham** [comment]
ok

**Comment by heizshubham** [comment]
Done, I've raised a PR Please merge it.
