### ISSUE TITLE
[Feat] Integrate a Chatbot for Instant User Support

### ISSUE THREAD

**Issue by sezallagwal** [sharmavikas4/MERN_BLOG#45]
### Description

Enhance the website's user experience by integrating a chatbot that provides instant answers to user inquiries. The chatbot should be easily accessible, provide relevant responses, and offer seamless assistance for common queries, improving user engagement and support.

Add a chatbot icon or button that floats on the bottom-right corner of the site.
When clicked, the chatbot window should expand with a smooth animation, displaying an input field and previous chat history.

The chatbot should respond to frequently asked questions (related to the FAQ section) and common inquiries about products or services.
Implement a fallback response for questions outside the chatbot's scope (e.g., "Sorry, I don't have an answer for that. Please contact our support team.").

please assign this to me under gssoc-ext and hacktoberfest

### Screenshots

https://github.com/user-attachments/assets/9617e9b6-e9fc-414c-9969-7f670d9985b5

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sharmavikas4** [comment]
@sezallagwal you can proceed
