### ISSUE TITLE
[BUG] blogController.js isn't working properly 

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [sharmavikas4/MERN_BLOG#47]
### Description

err variable is null when you attempt to access err.message 

when i add a new blog the server crashes

### Screenshots

![blogConrtroller](https://github.com/user-attachments/assets/fceff1cf-7cf3-4907-ad33-f7f6c755fe02)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sharmavikas4** [comment]
@ANJALIJAISWAL4213 are you uploading pdf instead of image

**Comment by ANJALIJAISWAL4213** [comment]
No it's an image

**Comment by sharmavikas4** [comment]
I am getting no such error in my local set up
