### ISSUE TITLE
[Documentation] Add Table to Display Repository Statistics in README.md

### ISSUE THREAD

**Issue by KGupta2601** [sharmavikas4/MERN_BLOG#48]
### Description

Issue Description:
The issue involves adding a well structured table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions at a glance.

Steps to Implement:
Create a table in the README.md file displaying the following repository statistics:
Stars
Forks
Open Issues
Open Pull Requests
Closed Pull Requests
Use markdown syntax to include badges or icons for each statistic.
Add dynamic links to the corresponding sections of the repository for easy access (e.g., link to the "Issues" or "Pull Requests" tabs).
Expected Behavior:
The README.md file will contain a neatly formatted table that displays real-time repository statistics, making the repository's activity more visible and engaging for contributors and users.

### Screenshots

![379103314-6c04cef6-2926-40b9-a18a-9bee50d63026](https://github.com/user-attachments/assets/44cbfbfc-e595-4708-b8e6-dfc766206cbe)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by KGupta2601** [comment]
@sharmavikas4 kindly assign me this issue with the labels of gssoc extended,hacktoberfest and level

**Comment by sharmavikas4** [comment]
@KGupta2601 Also can you redesign whole readme.

**Comment by KGupta2601** [comment]
@sharmavikas4 yes sure ...I will add the gssoc banner also and will update the contributors as well
