### ISSUE TITLE
[Feat]Added the security

### ISSUE THREAD

**Issue by Dipanita45** [sharmavikas4/MERN_BLOG#54]
### Description

Security of the website

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sharmavikas4** [comment]
Can you please elaborate a little . We already have secure routes due to which there is no such security breach

**Comment by Dipanita45** [comment]
I will add security file in.md extension

**Comment by Dipanita45** [comment]
Please assign me this issue

**Comment by sharmavikas4** [comment]
what will this do

**Comment by Dipanita45** [comment]
I will add security file in md extension that includes how to
report,vulnerability,... Etc

**Comment by sharmavikas4** [comment]
Go ahead @Dipanita45
